/**
 * XJ3395 — Application Layer
 * What this file handles: Handler for uploading an attachment.
 */
const fs = require('fs').promises;
const { Result } = require('../dto/result');
const { toApplicationDetailDto } = require('../mapper/application_mapper');
const { Attachment } = require('../../domain/model/attachment');

class UploadAttachmentHandler {
  constructor(repository, storageService) {
    this.repository = repository;
    this.storageService = storageService;
  }
  async handle(command) {
    const app = await this.repository.findById(command.applicationId);
    if (!app) throw new Error('Application not found');
    
    // Read the temp file generated by multer
    const fileBuffer = await fs.readFile(command.file.path);
    
    // Upload to R2 and get public URL
    const fileUrl = await this.storageService.uploadFile(
      fileBuffer, 
      command.file.originalname, 
      command.file.mimetype
    );
    
    app.attachments.push(new Attachment(null, command.file.originalname, fileUrl, command.documentType));
    await this.repository.save(app);

    // Clean up temp file
    try {
      await fs.unlink(command.file.path);
    } catch (err) {
      console.error(`Failed to clean up temp file: ${command.file.path}`, err);
    }

    return Result.success(toApplicationDetailDto(app), 'Attachment uploaded');
  }
}
module.exports = { UploadAttachmentHandler };
